### ISSUE TITLE
Can you provide me with the files so that I can translate this mod?

### ISSUE THREAD

**Issue by thefish12357** [hreintke/COI_MineDumpControl#2]
Hi~
I would like to try to translate this mod into Chinese to make it easier for me to play the game, can you provide me with a text configuration file?
I will return the translated text to you!

**Comment by hreintke** [comment]
Hi,
Currently there is no text configuration file. Text is hardcoded in the source.
Did not yet look into the translation options of COI, as if I want to implement that, I want to use the same system.

If have no actual plans to implement this, but will look into it to se the possibilities/difficulties.

The full actual source code is available, you cab take that and translate yourself, it's only a limited amount of text.
If you do that in a structural way, which can be used for other translations, I am happy to accept a PR.

**Comment by thefish12357** [comment]
Okay, if you need help with translations in the future, please contact me.
